version: "3.7"

services:
  db:
    container_name: feeds_db
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: feeds_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword